### ISSUE TITLE
Generacja Webstrony nie dziala

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#38]
[Ostatni build](https://readthedocs.org/projects/socsim/builds/9955289/):

>Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [ 25%] AbelianSandpileModel
reading sources... [ 50%] StandardWorkflow
reading sources... [ 75%] index
reading sources... [100%] jupyternotebooks

>/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))

>Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/socsim/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/socsim/checkouts/latest/docsrc/source/contents.rst not found

>Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/socsim/checkouts/latest/docsrc/source/contents.rst not found

To troche dziwne, bo projekt juz nie ma zadnych linkow na `contents.rst`.

[Tutaj](https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found) chyba jest rozwiazanie

**Comment by okmechak** [comment]
Wiarygodnie poprawilem: 808013f31df6075422a67ded6d4337d23a4af461

**Comment by StanczakDominik** [comment]
https://socsim.readthedocs.io/en/latest/

@okmechak bardzo wiarygodnie! To teraz mi jeszcze wytłumacz, dlaczego to działa i skąd wie...

spojrzałem na "Tutaj" (link do Stacka).

Wat.

W każdym razie działa, zamykamy, dobry fix! :)
